name: Android CI

on:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decode firebase file
      id: firebase_service_account_file
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'firebase_service_account.json'
        encodedString: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
    - name: Build with Gradle
      run: ./gradlew assembleEnvDevelopRelease appDistributionUploadEnvDevelopRelease && ./gradlew assembleEnvProdRelease appDistributionUploadEnvProdRelease
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.firebase_service_account_file.outputs.filePath }}